resource_registry:
  OS::TripleO::Server: /home/stack/compiled-templates/deployed-server/deployed-server.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: OS::Neutron::Port
  OS::TripleO::DeployedServer::Bootstrap: OS::Heat::None


  # Default nic config mappings
  OS::TripleO::ControllerDeployedServer::Net::SoftwareConfig: /home/stack/templates/net-config-static.yaml
  OS::TripleO::ComputeDeployedServer::Net::SoftwareConfig: /home/stack/templates/net-config-static-compute.yaml

parameter_defaults:
  ExternalNetCidr: '169.45.205.64/26'
  ExternalAllocationPools: [{'start': '169.45.205.100', 'end': '169.45.205.126'}]
  ExternalInterfaceDefaultRoute: '169.45.205.66'
  ExternalNetworkVlanID: 0
  InternalApiNetName: ''

  DnsServers: [8.8.8.8,1.1.1.1]
  NeutronNetworkType: 'vxlan'
  NeutronTunnelTypes: 'vxlan'
  NeutronPhysicalBridge: br-ex

  ControlFixedIPs: [{'ip_address':'10.149.23.100'}]
  PublicVirtualFixedIPs: [{'ip_address':'169.45.205.100'}]
